### ISSUE TITLE
Put management tasks outside of individual repos

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/meta#11]
Keep one standard `Makefile` for all repositories.

Maybe we can reuse tools by people who know how the magic of `Makefile` (hi, @osterman and @cloudposse team)?

See [build-harness](https://github.com/cloudposse/build-harness/) and [this Makefile](https://github.com/cloudposse/terraform-aws-alb/blob/master/Makefile), as a good example.

Each `terraform-aws-modules` repo should contain a list of required targets to do all management tasks, for example:
  - [ ] Validate code
  - [ ] Run examples
  - [ ] Update changelog
  - [ ] Create release
  - [ ] Update README
  - [ ] etc...

PS: The ultimate goal is to keep as little as possible duplication in each Terraform module repositories.

Feedback from everyone, especially @barryib @bryantbiggs @max-rocket-internet is appreciated.

**Comment by bryantbiggs** [comment]
here's one example to start I just threw together https://gist.github.com/bryantbiggs/ab576e5718b4581083885e030b4b0765
