### ISSUE TITLE
Only allow squash merging in repos

### ISSUE THREAD

**Issue by barryib** [terraform-aws-modules/meta#2]
It would be nice to allow squash merging only in repos.

cc @max-rocket-internet 

![image](https://user-images.githubusercontent.com/550783/77004870-1f3ba180-6960-11ea-87d7-434dfb9c8da1.png)

**Comment by antonbabenko** [comment]
I agree.

Currently, `Allow merge commits` is needed by `githubfile` Terraform provider which is updating files on GitHub repositories. Without that it produces this error:

    Error: failed to create commit: failed to merge PR: HTTP 405: PUT https://api.github.com/repos/terraform-aws-modules/terraform-aws-eks/pulls/807/merge: 405 Merge commits are not allowed on this repository. []

I think we will need to make squash commits when merging ourselves and allow merge commits only for tools we can't easily configure (eg, githubfile provider does not have option to squash commits).

**Comment by barryib** [comment]
Hummm... maybe we should open a feature request on githubfile repo to add option to use `squash and merge` api  https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button `merge_method : squash `?

![image](https://user-images.githubusercontent.com/550783/77115254-4c568580-6a2e-11ea-9dda-749f7e596aa1.png)

**Comment by antonbabenko** [comment]
Yes, it is a good idea to get a proper fix in the provider. I will open it tomorrow morning if you don't mind.

**Comment by barryib** [comment]
It sounds that the feature won't be hard to add. https://github.com/form3tech-oss/go-github-utils/blob/master/pkg/commit/commit.go#L137 we can quickly add an `PullRequestOptions` the merge function https://godoc.org/github.com/google/go-github/github#PullRequestsService.Merge 

https://godoc.org/github.com/google/go-github/github#PullRequestOptions
