### ISSUE TITLE
update issue templates to more interactive and new format

### ISSUE THREAD

**Issue by daroga0002** [terraform-aws-modules/meta#23]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
No

## Describe the solution you'd like.
Updater issue templates to new format and more interactive way as currently:
![image](https://user-images.githubusercontent.com/20227477/130930332-1d9e146a-71b7-4507-bb82-aee065cea5e4.png)

I am proposing that issues will have different templates with questions for each kind.

## Describe alternatives you've considered.
something what is described here https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by daroga0002** [comment]
I will try to find some time and write some potencial templates

**Comment by antonbabenko** [comment]
We will need to have a template shared across multiple repositories (probably all `terraform-aws-modules` can share a single template).

It is better to have such meta-work here in this repo.

**Comment by bryantbiggs** [comment]
these are all automatically controlled through the [.github](https://github.com/terraform-aws-modules/.github) repo - see more here https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

@daroga0002 if you delete those issue and PR templates from the EKS repo then they will inherit and use the default templates setup here https://github.com/terraform-aws-modules/.github
