### ISSUE TITLE
Update release workflow to only run on source repos

### ISSUE THREAD

**Issue by bryantbiggs** [terraform-aws-modules/meta#25]
## Description
We should add in a conditional check for the release workflow so that it only runs on the source repos, and not on forked copies. Its as simple as adding in `if: github.repository_owner == 'terraform-aws-modules'` - Ref https://github.com/prisma/prisma/issues/3539

**Comment by antonbabenko** [comment]
Hi @bryantbiggs 

Thanks for all these 33 PRs! All merged now :)
