### ISSUE TITLE
Unify CHANGELOG across all repositories

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/meta#3]
19.3.2020 - I made an update to the template file `CHANGELOG.tpl.md` which we can use for most of the repositories. Here is the commit - https://github.com/terraform-aws-modules/terraform-aws-notify-slack/commit/6ed9733a08685b5946796cb69affb7fa602e670a , [recent version in master]( https://github.com/terraform-aws-modules/terraform-aws-notify-slack/blob/master/.chglog/CHANGELOG.tpl.md).

Since there was no unified naming convention implemented across all repositories I don’t see how we can use the single template just yet.

I propose to:
- [x] Keep separate [CHANGELOG.tpl.md template](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/.chglog/CHANGELOG.tpl.md) for `terraform-aws-eks` repository.
- [x]  Keep standard template for all other repositories and manage it via this meta repo.
- [ ]  Enforce PR titles to follow conventional commits (using [Semantic Pull Request](https://github.com/amannn/action-semantic-pull-request) GH Actions).

We should aim to use [CHANGELOG.tpl.md from terraform-aws-eks module](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/.chglog/CHANGELOG.tpl.md) in other repositories, too.

**Comment by antonbabenko** [comment]
@barryib Feedback is welcome

**Comment by barryib** [comment]
> 19.3.2020 - I made an update to the template file CHANGELOG.tpl.md which we can use for most of the repositories. Here is the commit - terraform-aws-modules/terraform-aws-notify-slack@6ed9733 , recent version in master.

I think you can use commit filter https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/.chglog/config.yml#L10-L19 instead of lot of `if else` in your template.

> Keep separate CHANGELOG.tpl.md template for terraform-aws-eks repository.

I think we can have the same template for all repo. We just have to agree with the changelog style and follow https://www.conventionalcommits.org/en/v1.0.0/ for commits naming convention.

Move the old changelog to a different location like what we did with [CHANGELOG.pre-v11.0.0.md](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/CHANGELOG.pre-v11.0.0.md)

**Comment by antonbabenko** [comment]
I tried to use commit filters, but they only work when `Type` is set in `header` with `pattern_maps` (https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/.chglog/config.yml#L33-L37).

In cases where commit subjects are different, we can't use `pattern: "^(.+)\\s*:\\s*(.+)$"` but should use something generic like - `pattern: "^(.+)*$"`. With such generic pattern we can't map match group to `Type`.

I would like to update lots of `if else` with something more elegant, but couldn't figure out what works for both - old (unstructured commits) and new (following `conventional commits`).

---

### Single `CHANGELOG.tpl.md` across all repositories.

How can we have `TAG_QUERY` argument different for each repository (`Makefile` is the same for all repos)? A new CHANGELOG template will be used for all tags starting from `tag X`.

**Comment by barryib** [comment]
> I tried to use commit filters, but they only work when Type is set in header with pattern_maps (https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/.chglog/config.yml#L33-L37).

Maybe we should just follow [conventional commit convention](https://www.conventionalcommits.org/en/v1.0.0/) or http://keepachangelog.com/ and use types ?

**Comment by bryantbiggs** [comment]
I've started switching over to using conventional commits - makes it so much easier to generate CHANGELOGs. We'd have to check this somehow via something like Github actions or whatever

**Comment by antonbabenko** [comment]
Yesterday I have enabled https://github.com/zeke/semantic-pull-requests on all repositories for all PRs (for example, https://github.com/terraform-aws-modules/terraform-aws-notify-slack/pull/76 says "Semantic Pull Request — ready to be squashed").

Here is the list of supported types - https://github.com/commitizen/conventional-commit-types/blob/master/index.json

**Comment by antonbabenko** [comment]
@barryib Yes, we use conventional commits for new commits, but the question is still open:

> ### Single CHANGELOG.tpl.md across all repositories.
> How can we have TAG_QUERY argument different for each repository (Makefile is the same for all repos)? A new CHANGELOG template will be used for all tags starting from tag X.

**Comment by barryib** [comment]
> Single CHANGELOG.tpl.md across all repositories.
How can we have TAG_QUERY argument different for each repository (Makefile is the same for all repos)? A new CHANGELOG template will be used for all tags starting from tag X.

Humm... just few ideas :
- Use a special commit message and find the corresponding tag ? `git-chglog $(git describe --tags $(git log --all --grep='COMMIT MESSAGE TO MARK NEW CHANGELOG'))..`
- Add a file with the tag and use it in the Makefile ? Maybe in `.chglog/tag` ? 
- Include a file in Makefile without error (`-include makefile/chglog.mk`) which will have a variable with the tag ?

**Comment by bryantbiggs** [comment]
I think this one is complete now

**Comment by dhoppe** [comment]
Just a quick idea. Maybe you should look into these GitHub actions. 
* https://github.com/terraform-docs/gh-actions
* https://github.com/google-github-actions/release-please-action

**Comment by antonbabenko** [comment]
We are good with CHANGELOG already.

The only bit left is related to semantic titles in PR, which we can get using this GH Action - https://github.com/amannn/action-semantic-pull-request

**Comment by dhoppe** [comment]
I just thought because `GoogleCloudPlatform/release-please-action` is able to create releases, based on `feat:` or `fix:`. But `amannn/action-semantic-pull-request` is interesting, because `GoogleCloudPlatform/release-please-action`  fails to recognise new releases, if the commit message contains `feat:` or `fix:` but not the title of a pull request.

**Comment by antonbabenko** [comment]
@dhoppe We already have semantic release action in all repositories. Based on the PR title, we make a patch, minor, or major releases ([example](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/releases)). So far so good :)
