### ISSUE TITLE
Terraform AWS SSO Module

### ISSUE THREAD

**Issue by victorcechinel** [terraform-aws-modules/meta#34]
## Is your request related to a new offering from AWS?
This functionality is available from the official AWS provider version 5.0.1.

- [Terraform SSO Admin](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_account_assignment);
- [Terraform SSO Identity Store](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group);

## Is your request related to a problem? Please describe.
Creation of a new repository to develop a Terraform module that supports SSO Admin and SSO Identity Store.

## Describe the solution you'd like.
I want to contribute to the community and create a module for SSO, following the guidelines.

## Describe alternatives you've considered.
I work with my own module, but it is interesting that the community has its own.

**Comment by victorcechinel** [comment]
I would like to be able to create the PR with the implementations for creating this repository. 🚧

**Comment by antonbabenko** [comment]
Please make the code as complete as possible, which matches existing [Terraform AWS modules](https://github.com/terraform-aws-modules), in your GitHub account. Once ready, we will review it, and you can transfer it to `terraform-aws-modules` organization.

**Comment by victorcechinel** [comment]
@antonbabenko I'm close this issue and then open a new one, ok?

**Comment by antonbabenko** [comment]
Sure, as you wish. Feel free to mention my username in the repository you are working on.

**Comment by victorcechinel** [comment]
Thanks 🙏
